// <auto-generated />
namespace VeronaTour.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Implimitation_Logging : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Implimitation_Logging));
        
        string IMigrationMetadata.Id
        {
            get { return "202003311234340_Implimitation_Logging"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
